title: Roxx-Mixx Duo
description: |
  Melbourne band
  Covering all styles, eras for events, parties & venues
owner: Roxx-Mixx Duo # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: roxxmixx.duo@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://roxxmixxduo.github.io"
social:
  facebook-official: https://facebook.com/roxx.mixx.5
  email: roxxmixx.duo@gmail.com


# Build settings
markdown: kramdown
#sass:
#  style: compressed
